### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ALI444000** [rc-chuah/Kali-Nethunter-In-Termux#2]
Initializing download: https://images.kali.org/nethunter/kalifs-arm64-full.tar.xz
ERROR 404: Not Found.

How fix this error?

**Comment by rc-chuah** [comment]
> Initializing download: https://images.kali.org/nethunter/kalifs-arm64-full.tar.xz
> ERROR 404: Not Found.
> 
> How fix this error?

I Will Fix This Error Soon, The Error Is Because Of Kali Linux FS Mirror Link Has Changed.

**Comment by rc-chuah** [comment]
Thank You For Bringing This Bug To My Attention. I Have Addressed The Issue, And Have Tested It To Ensure It Is Fixed. I Apologize For Any Inconvenience This May Have Caused And I Appreciate Your Patience.

### Install Kali Nethunter Full Version
1. Download script in **HOME** `wget https://raw.githubusercontent.com/rc-chuah/Kali-Nethunter-In-Termux/master/install-nethunter-full-termux`
2. Give execution permission `chmod +x install-nethunter-full-termux`
3. Run script `./install-nethunter-full-termux`
4. Now just start kali nethunter `nethunter`
